/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Uaffiche (void)
{
  GtkWidget *Uaffiche;
  GtkWidget *fixed1;
  GtkWidget *treeviewU;
  GtkWidget *UsearchEntry;
  GtkWidget *eventbox1;
  GtkWidget *Ubutton_AfficherByRole;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image12;
  GtkWidget *label28;
  GtkWidget *eventbox2;
  GtkWidget *Ucombobox_filtre;
  GtkWidget *eventbox3;
  GtkWidget *UsearchButton;
  GtkWidget *image1;
  GtkWidget *eventbox5;
  GtkWidget *label1;
  GtkWidget *eventbox6;
  GtkWidget *UajoutWidget;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *eventbox7;
  GtkWidget *UmodifierWidget;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *eventbox8;
  GtkWidget *UsupprimerWidget;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *eventbox9;
  GtkWidget *Uactualiser;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label6;
  GtkWidget *eventbox10;
  GtkWidget *UstatistiqueWidget;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label7;
  GtkWidget *eventbox12;
  GtkWidget *image19;
  GtkWidget *image20;

  Uaffiche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Uaffiche, 990, 811);
  gtk_window_set_title (GTK_WINDOW (Uaffiche), _("Gestion des utilisateurs"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Uaffiche), fixed1);

  treeviewU = gtk_tree_view_new ();
  gtk_widget_show (treeviewU);
  gtk_fixed_put (GTK_FIXED (fixed1), treeviewU, 32, 232);
  gtk_widget_set_size_request (treeviewU, 664, 464);

  UsearchEntry = gtk_entry_new ();
  gtk_widget_show (UsearchEntry);
  gtk_fixed_put (GTK_FIXED (fixed1), UsearchEntry, 344, 152);
  gtk_widget_set_size_request (UsearchEntry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UsearchEntry), 8226);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox1, 88, 184);
  gtk_widget_set_size_request (eventbox1, 145, 32);

  Ubutton_AfficherByRole = gtk_button_new ();
  gtk_widget_show (Ubutton_AfficherByRole);
  gtk_container_add (GTK_CONTAINER (eventbox1), Ubutton_AfficherByRole);
  gtk_widget_set_size_request (Ubutton_AfficherByRole, 145, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (Ubutton_AfficherByRole), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image12 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox11), image12, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Filtrer By Role"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox11), label28, FALSE, FALSE, 0);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox2, 64, 152);
  gtk_widget_set_size_request (eventbox2, 189, 29);

  Ucombobox_filtre = gtk_combo_box_entry_new_text ();
  gtk_widget_show (Ucombobox_filtre);
  gtk_container_add (GTK_CONTAINER (eventbox2), Ucombobox_filtre);
  gtk_widget_set_size_request (Ucombobox_filtre, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (Ucombobox_filtre), _("medecin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (Ucombobox_filtre), _("infemier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (Ucombobox_filtre), _("ets"));

  eventbox3 = gtk_event_box_new ();
  gtk_widget_show (eventbox3);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox3, 528, 152);
  gtk_widget_set_size_request (eventbox3, 58, 29);

  UsearchButton = gtk_button_new ();
  gtk_widget_show (UsearchButton);
  gtk_container_add (GTK_CONTAINER (eventbox3), UsearchButton);
  gtk_widget_set_size_request (UsearchButton, 58, 29);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (UsearchButton), image1);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_show (eventbox5);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox5, 408, 64);
  gtk_widget_set_size_request (eventbox5, 193, 17);

  label1 = gtk_label_new (_("Gestion des utilisateurs"));
  gtk_widget_show (label1);
  gtk_container_add (GTK_CONTAINER (eventbox5), label1);
  gtk_widget_set_size_request (label1, 193, 17);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox6, 720, 176);
  gtk_widget_set_size_request (eventbox6, 219, 58);

  UajoutWidget = gtk_button_new ();
  gtk_widget_show (UajoutWidget);
  gtk_container_add (GTK_CONTAINER (eventbox6), UajoutWidget);
  gtk_widget_set_size_request (UajoutWidget, 219, 58);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (UajoutWidget), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  eventbox7 = gtk_event_box_new ();
  gtk_widget_show (eventbox7);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox7, 720, 296);
  gtk_widget_set_size_request (eventbox7, 219, 58);

  UmodifierWidget = gtk_button_new ();
  gtk_widget_show (UmodifierWidget);
  gtk_container_add (GTK_CONTAINER (eventbox7), UmodifierWidget);
  gtk_widget_set_size_request (UmodifierWidget, 219, 58);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (UmodifierWidget), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Modification"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox8, 720, 416);
  gtk_widget_set_size_request (eventbox8, 219, 58);

  UsupprimerWidget = gtk_button_new ();
  gtk_widget_show (UsupprimerWidget);
  gtk_container_add (GTK_CONTAINER (eventbox8), UsupprimerWidget);
  gtk_widget_set_size_request (UsupprimerWidget, 219, 58);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (UsupprimerWidget), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox9, 720, 560);
  gtk_widget_set_size_request (eventbox9, 219, 58);

  Uactualiser = gtk_button_new ();
  gtk_widget_show (Uactualiser);
  gtk_container_add (GTK_CONTAINER (eventbox9), Uactualiser);
  gtk_widget_set_size_request (Uactualiser, 219, 58);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (Uactualiser), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);

  eventbox10 = gtk_event_box_new ();
  gtk_widget_show (eventbox10);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox10, 720, 696);
  gtk_widget_set_size_request (eventbox10, 219, 58);

  UstatistiqueWidget = gtk_button_new ();
  gtk_widget_show (UstatistiqueWidget);
  gtk_container_add (GTK_CONTAINER (eventbox10), UstatistiqueWidget);
  gtk_widget_set_size_request (UstatistiqueWidget, 219, 58);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (UstatistiqueWidget), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Statistique"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox6), label7, FALSE, FALSE, 0);

  eventbox12 = gtk_event_box_new ();
  gtk_widget_show (eventbox12);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox12, 128, 0);
  gtk_widget_set_size_request (eventbox12, 232, 152);

  image19 = create_pixmap (Uaffiche, "image-removebg-preview.png");
  gtk_widget_show (image19);
  gtk_container_add (GTK_CONTAINER (eventbox12), image19);
  gtk_widget_set_size_request (image19, 232, 152);

  image20 = create_pixmap (Uaffiche, "Screenshot_2023-10-30_123530-removebg.png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed1), image20, 8, 0);
  gtk_widget_set_size_request (image20, 1016, 808);

  g_signal_connect ((gpointer) treeviewU, "row_activated",
                    G_CALLBACK (on_treeviewU_row_activated),
                    NULL);
  g_signal_connect ((gpointer) Ubutton_AfficherByRole, "clicked",
                    G_CALLBACK (on_Ubutton_AfficherByRole_clicked),
                    NULL);
  g_signal_connect ((gpointer) UsearchButton, "clicked",
                    G_CALLBACK (on_UsearchButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) UajoutWidget, "clicked",
                    G_CALLBACK (on_UajoutWidget_clicked),
                    NULL);
  g_signal_connect ((gpointer) UmodifierWidget, "clicked",
                    G_CALLBACK (on_UmodifierWidget_clicked),
                    NULL);
  g_signal_connect ((gpointer) UsupprimerWidget, "clicked",
                    G_CALLBACK (on_UsupprimerWidget_clicked),
                    NULL);
  g_signal_connect ((gpointer) Uactualiser, "clicked",
                    G_CALLBACK (on_Uactualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) UstatistiqueWidget, "clicked",
                    G_CALLBACK (on_UstatistiqueWidget_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Uaffiche, Uaffiche, "Uaffiche");
  GLADE_HOOKUP_OBJECT (Uaffiche, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Uaffiche, treeviewU, "treeviewU");
  GLADE_HOOKUP_OBJECT (Uaffiche, UsearchEntry, "UsearchEntry");
  GLADE_HOOKUP_OBJECT (Uaffiche, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (Uaffiche, Ubutton_AfficherByRole, "Ubutton_AfficherByRole");
  GLADE_HOOKUP_OBJECT (Uaffiche, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Uaffiche, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Uaffiche, image12, "image12");
  GLADE_HOOKUP_OBJECT (Uaffiche, label28, "label28");
  GLADE_HOOKUP_OBJECT (Uaffiche, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (Uaffiche, Ucombobox_filtre, "Ucombobox_filtre");
  GLADE_HOOKUP_OBJECT (Uaffiche, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (Uaffiche, UsearchButton, "UsearchButton");
  GLADE_HOOKUP_OBJECT (Uaffiche, image1, "image1");
  GLADE_HOOKUP_OBJECT (Uaffiche, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (Uaffiche, label1, "label1");
  GLADE_HOOKUP_OBJECT (Uaffiche, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (Uaffiche, UajoutWidget, "UajoutWidget");
  GLADE_HOOKUP_OBJECT (Uaffiche, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Uaffiche, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Uaffiche, image3, "image3");
  GLADE_HOOKUP_OBJECT (Uaffiche, label3, "label3");
  GLADE_HOOKUP_OBJECT (Uaffiche, eventbox7, "eventbox7");
  GLADE_HOOKUP_OBJECT (Uaffiche, UmodifierWidget, "UmodifierWidget");
  GLADE_HOOKUP_OBJECT (Uaffiche, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Uaffiche, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Uaffiche, image4, "image4");
  GLADE_HOOKUP_OBJECT (Uaffiche, label4, "label4");
  GLADE_HOOKUP_OBJECT (Uaffiche, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (Uaffiche, UsupprimerWidget, "UsupprimerWidget");
  GLADE_HOOKUP_OBJECT (Uaffiche, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Uaffiche, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Uaffiche, image5, "image5");
  GLADE_HOOKUP_OBJECT (Uaffiche, label5, "label5");
  GLADE_HOOKUP_OBJECT (Uaffiche, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (Uaffiche, Uactualiser, "Uactualiser");
  GLADE_HOOKUP_OBJECT (Uaffiche, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Uaffiche, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Uaffiche, image6, "image6");
  GLADE_HOOKUP_OBJECT (Uaffiche, label6, "label6");
  GLADE_HOOKUP_OBJECT (Uaffiche, eventbox10, "eventbox10");
  GLADE_HOOKUP_OBJECT (Uaffiche, UstatistiqueWidget, "UstatistiqueWidget");
  GLADE_HOOKUP_OBJECT (Uaffiche, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Uaffiche, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Uaffiche, image7, "image7");
  GLADE_HOOKUP_OBJECT (Uaffiche, label7, "label7");
  GLADE_HOOKUP_OBJECT (Uaffiche, eventbox12, "eventbox12");
  GLADE_HOOKUP_OBJECT (Uaffiche, image19, "image19");
  GLADE_HOOKUP_OBJECT (Uaffiche, image20, "image20");

  return Uaffiche;
}

GtkWidget*
create_Uajoute (void)
{
  GtkWidget *Uajoute;
  GtkWidget *fixed2;
  GtkWidget *UcinEntryAjout;
  GtkWidget *UnomEntryAjout;
  GtkObject *UjjSpinAjout_adj;
  GtkWidget *UjjSpinAjout;
  GtkObject *UmmSpinAjout_adj;
  GtkWidget *UmmSpinAjout;
  GtkObject *UyySpinAjout_adj;
  GtkWidget *UyySpinAjout;
  GtkWidget *UprenomEntryAjout;
  GtkWidget *UnumEntryAjout;
  GtkWidget *UloginEntryAjout;
  GtkWidget *UmdpEntryAjout;
  GtkWidget *eventbox13;
  GtkWidget *label19;
  GtkWidget *eventbox14;
  GtkWidget *label9;
  GtkWidget *eventbox15;
  GtkWidget *label8;
  GtkWidget *eventbox16;
  GtkWidget *label36;
  GtkWidget *eventbox17;
  GtkWidget *label14;
  GtkWidget *eventbox18;
  GtkWidget *label11;
  GtkWidget *eventbox19;
  GtkWidget *label12;
  GtkWidget *eventbox20;
  GtkWidget *label13;
  GtkWidget *eventbox21;
  GtkWidget *label15;
  GtkWidget *eventbox22;
  GtkWidget *UgenreHommeAjout;
  GSList *UgenreHommeAjout_group = NULL;
  GtkWidget *eventbox23;
  GtkWidget *UgenreFemmeAjout;
  GtkWidget *eventbox24;
  GtkWidget *label16;
  GtkWidget *eventbox25;
  GtkWidget *UregionComboAjout;
  GtkWidget *eventbox26;
  GtkWidget *label17;
  GtkWidget *eventbox27;
  GtkWidget *label18;
  GtkWidget *eventbox28;
  GtkWidget *UroleComboAjout;
  GtkWidget *eventbox29;
  GtkWidget *label37;
  GtkWidget *eventbox30;
  GtkWidget *label38;
  GtkWidget *eventbox31;
  GtkWidget *UafficherMdpAjout;
  GtkWidget *eventbox32;
  GtkWidget *UcontroleSaisiAjout;
  GtkWidget *eventbox33;
  GtkWidget *UannulerAjoutButton;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label20;
  GtkWidget *eventbox34;
  GtkWidget *UajoutButton;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label21;
  GtkWidget *eventbox35;
  GtkWidget *image21;
  GtkWidget *image22;

  Uajoute = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Uajoute, 921, 897);
  gtk_window_set_title (GTK_WINDOW (Uajoute), _("Ajout d'un utilisateur"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Uajoute), fixed2);

  UcinEntryAjout = gtk_entry_new ();
  gtk_widget_show (UcinEntryAjout);
  gtk_fixed_put (GTK_FIXED (fixed2), UcinEntryAjout, 344, 144);
  gtk_widget_set_size_request (UcinEntryAjout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UcinEntryAjout), 8226);

  UnomEntryAjout = gtk_entry_new ();
  gtk_widget_show (UnomEntryAjout);
  gtk_fixed_put (GTK_FIXED (fixed2), UnomEntryAjout, 344, 192);
  gtk_widget_set_size_request (UnomEntryAjout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UnomEntryAjout), 8226);

  UjjSpinAjout_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  UjjSpinAjout = gtk_spin_button_new (GTK_ADJUSTMENT (UjjSpinAjout_adj), 1, 0);
  gtk_widget_show (UjjSpinAjout);
  gtk_fixed_put (GTK_FIXED (fixed2), UjjSpinAjout, 368, 344);
  gtk_widget_set_size_request (UjjSpinAjout, 60, 27);

  UmmSpinAjout_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  UmmSpinAjout = gtk_spin_button_new (GTK_ADJUSTMENT (UmmSpinAjout_adj), 1, 0);
  gtk_widget_show (UmmSpinAjout);
  gtk_fixed_put (GTK_FIXED (fixed2), UmmSpinAjout, 536, 344);
  gtk_widget_set_size_request (UmmSpinAjout, 60, 27);

  UyySpinAjout_adj = gtk_adjustment_new (2023, 1950, 2024, 1, 10, 10);
  UyySpinAjout = gtk_spin_button_new (GTK_ADJUSTMENT (UyySpinAjout_adj), 1, 0);
  gtk_widget_show (UyySpinAjout);
  gtk_fixed_put (GTK_FIXED (fixed2), UyySpinAjout, 720, 344);
  gtk_widget_set_size_request (UyySpinAjout, 60, 27);

  UprenomEntryAjout = gtk_entry_new ();
  gtk_widget_show (UprenomEntryAjout);
  gtk_fixed_put (GTK_FIXED (fixed2), UprenomEntryAjout, 344, 248);
  gtk_widget_set_size_request (UprenomEntryAjout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UprenomEntryAjout), 8226);

  UnumEntryAjout = gtk_entry_new ();
  gtk_widget_show (UnumEntryAjout);
  gtk_fixed_put (GTK_FIXED (fixed2), UnumEntryAjout, 312, 520);
  gtk_widget_set_size_request (UnumEntryAjout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UnumEntryAjout), 8226);

  UloginEntryAjout = gtk_entry_new ();
  gtk_widget_show (UloginEntryAjout);
  gtk_fixed_put (GTK_FIXED (fixed2), UloginEntryAjout, 328, 624);
  gtk_widget_set_size_request (UloginEntryAjout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UloginEntryAjout), 8226);

  UmdpEntryAjout = gtk_entry_new ();
  gtk_widget_show (UmdpEntryAjout);
  gtk_fixed_put (GTK_FIXED (fixed2), UmdpEntryAjout, 328, 680);
  gtk_widget_set_size_request (UmdpEntryAjout, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (UmdpEntryAjout), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (UmdpEntryAjout), 8226);

  eventbox13 = gtk_event_box_new ();
  gtk_widget_show (eventbox13);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox13, 304, 56);
  gtk_widget_set_size_request (eventbox13, 300, 17);

  label19 = gtk_label_new (_("Ajouter un utilisateur"));
  gtk_widget_show (label19);
  gtk_container_add (GTK_CONTAINER (eventbox13), label19);
  gtk_widget_set_size_request (label19, 300, 17);

  eventbox14 = gtk_event_box_new ();
  gtk_widget_show (eventbox14);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox14, 280, 152);
  gtk_widget_set_size_request (eventbox14, 49, 17);

  label9 = gtk_label_new (_("Cin"));
  gtk_widget_show (label9);
  gtk_container_add (GTK_CONTAINER (eventbox14), label9);
  gtk_widget_set_size_request (label9, 49, 17);

  eventbox15 = gtk_event_box_new ();
  gtk_widget_show (eventbox15);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox15, 272, 200);
  gtk_widget_set_size_request (eventbox15, 49, 17);

  label8 = gtk_label_new (_("Nom"));
  gtk_widget_show (label8);
  gtk_container_add (GTK_CONTAINER (eventbox15), label8);
  gtk_widget_set_size_request (label8, 49, 17);

  eventbox16 = gtk_event_box_new ();
  gtk_widget_show (eventbox16);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox16, 256, 256);
  gtk_widget_set_size_request (eventbox16, 54, 17);

  label36 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label36);
  gtk_container_add (GTK_CONTAINER (eventbox16), label36);
  gtk_widget_set_size_request (label36, 54, 17);

  eventbox17 = gtk_event_box_new ();
  gtk_widget_show (eventbox17);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox17, 208, 352);
  gtk_widget_set_size_request (eventbox17, 49, 17);

  label14 = gtk_label_new (_("Date"));
  gtk_widget_show (label14);
  gtk_container_add (GTK_CONTAINER (eventbox17), label14);
  gtk_widget_set_size_request (label14, 49, 17);

  eventbox18 = gtk_event_box_new ();
  gtk_widget_show (eventbox18);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox18, 296, 352);
  gtk_widget_set_size_request (eventbox18, 49, 17);

  label11 = gtk_label_new (_("Jour"));
  gtk_widget_show (label11);
  gtk_container_add (GTK_CONTAINER (eventbox18), label11);
  gtk_widget_set_size_request (label11, 49, 17);

  eventbox19 = gtk_event_box_new ();
  gtk_widget_show (eventbox19);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox19, 480, 352);
  gtk_widget_set_size_request (eventbox19, 49, 17);

  label12 = gtk_label_new (_("Mois"));
  gtk_widget_show (label12);
  gtk_container_add (GTK_CONTAINER (eventbox19), label12);
  gtk_widget_set_size_request (label12, 49, 17);

  eventbox20 = gtk_event_box_new ();
  gtk_widget_show (eventbox20);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox20, 656, 352);
  gtk_widget_set_size_request (eventbox20, 49, 17);

  label13 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label13);
  gtk_container_add (GTK_CONTAINER (eventbox20), label13);
  gtk_widget_set_size_request (label13, 49, 17);

  eventbox21 = gtk_event_box_new ();
  gtk_widget_show (eventbox21);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox21, 208, 408);
  gtk_widget_set_size_request (eventbox21, 49, 17);

  label15 = gtk_label_new (_("Genre"));
  gtk_widget_show (label15);
  gtk_container_add (GTK_CONTAINER (eventbox21), label15);
  gtk_widget_set_size_request (label15, 49, 17);

  eventbox22 = gtk_event_box_new ();
  gtk_widget_show (eventbox22);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox22, 304, 408);
  gtk_widget_set_size_request (eventbox22, 116, 24);

  UgenreHommeAjout = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (UgenreHommeAjout);
  gtk_container_add (GTK_CONTAINER (eventbox22), UgenreHommeAjout);
  gtk_widget_set_size_request (UgenreHommeAjout, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (UgenreHommeAjout), UgenreHommeAjout_group);
  UgenreHommeAjout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (UgenreHommeAjout));

  eventbox23 = gtk_event_box_new ();
  gtk_widget_show (eventbox23);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox23, 416, 408);
  gtk_widget_set_size_request (eventbox23, 116, 24);

  UgenreFemmeAjout = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (UgenreFemmeAjout);
  gtk_container_add (GTK_CONTAINER (eventbox23), UgenreFemmeAjout);
  gtk_widget_set_size_request (UgenreFemmeAjout, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (UgenreFemmeAjout), UgenreHommeAjout_group);
  UgenreHommeAjout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (UgenreFemmeAjout));

  eventbox24 = gtk_event_box_new ();
  gtk_widget_show (eventbox24);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox24, 208, 464);
  gtk_widget_set_size_request (eventbox24, 73, 17);

  label16 = gtk_label_new (_("Region"));
  gtk_widget_show (label16);
  gtk_container_add (GTK_CONTAINER (eventbox24), label16);
  gtk_widget_set_size_request (label16, 73, 17);

  eventbox25 = gtk_event_box_new ();
  gtk_widget_show (eventbox25);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox25, 304, 456);
  gtk_widget_set_size_request (eventbox25, 189, 29);

  UregionComboAjout = gtk_combo_box_entry_new_text ();
  gtk_widget_show (UregionComboAjout);
  gtk_container_add (GTK_CONTAINER (eventbox25), UregionComboAjout);
  gtk_widget_set_size_request (UregionComboAjout, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Beja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Ben arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Touzeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Jandouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Zaghouane"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Seliana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Sidi bouzid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Gebelli"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("kasserine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Gafsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Kairouane"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("el Kef"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Mednine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Mannouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboAjout), _("Nabeul"));

  eventbox26 = gtk_event_box_new ();
  gtk_widget_show (eventbox26);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox26, 208, 528);
  gtk_widget_set_size_request (eventbox26, 88, 17);

  label17 = gtk_label_new (_("Telephone"));
  gtk_widget_show (label17);
  gtk_container_add (GTK_CONTAINER (eventbox26), label17);
  gtk_widget_set_size_request (label17, 88, 17);

  eventbox27 = gtk_event_box_new ();
  gtk_widget_show (eventbox27);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox27, 216, 584);
  gtk_widget_set_size_request (eventbox27, 72, 17);

  label18 = gtk_label_new (_("Role"));
  gtk_widget_show (label18);
  gtk_container_add (GTK_CONTAINER (eventbox27), label18);
  gtk_widget_set_size_request (label18, 72, 17);

  eventbox28 = gtk_event_box_new ();
  gtk_widget_show (eventbox28);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox28, 312, 576);
  gtk_widget_set_size_request (eventbox28, 189, 29);

  UroleComboAjout = gtk_combo_box_entry_new_text ();
  gtk_widget_show (UroleComboAjout);
  gtk_container_add (GTK_CONTAINER (eventbox28), UroleComboAjout);
  gtk_widget_set_size_request (UroleComboAjout, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (UroleComboAjout), _("medecin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UroleComboAjout), _("infemier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UroleComboAjout), _("ets"));

  eventbox29 = gtk_event_box_new ();
  gtk_widget_show (eventbox29);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox29, 232, 640);
  gtk_widget_set_size_request (eventbox29, 49, 17);

  label37 = gtk_label_new (_("Login"));
  gtk_widget_show (label37);
  gtk_container_add (GTK_CONTAINER (eventbox29), label37);
  gtk_widget_set_size_request (label37, 49, 17);

  eventbox30 = gtk_event_box_new ();
  gtk_widget_show (eventbox30);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox30, 208, 680);
  gtk_widget_set_size_request (eventbox30, 113, 17);

  label38 = gtk_label_new (_("Mot de passe "));
  gtk_widget_show (label38);
  gtk_container_add (GTK_CONTAINER (eventbox30), label38);
  gtk_widget_set_size_request (label38, 113, 17);

  eventbox31 = gtk_event_box_new ();
  gtk_widget_show (eventbox31);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox31, 520, 680);
  gtk_widget_set_size_request (eventbox31, 181, 24);

  UafficherMdpAjout = gtk_check_button_new_with_mnemonic (_("Afficher le mot de passe"));
  gtk_widget_show (UafficherMdpAjout);
  gtk_container_add (GTK_CONTAINER (eventbox31), UafficherMdpAjout);
  gtk_widget_set_size_request (UafficherMdpAjout, 181, 24);

  eventbox32 = gtk_event_box_new ();
  gtk_widget_show (eventbox32);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox32, 312, 720);
  gtk_widget_set_size_request (eventbox32, 300, 25);

  UcontroleSaisiAjout = gtk_label_new ("");
  gtk_widget_show (UcontroleSaisiAjout);
  gtk_container_add (GTK_CONTAINER (eventbox32), UcontroleSaisiAjout);
  gtk_widget_set_size_request (UcontroleSaisiAjout, 300, 25);

  eventbox33 = gtk_event_box_new ();
  gtk_widget_show (eventbox33);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox33, 224, 752);
  gtk_widget_set_size_request (eventbox33, 219, 58);

  UannulerAjoutButton = gtk_button_new ();
  gtk_widget_show (UannulerAjoutButton);
  gtk_container_add (GTK_CONTAINER (eventbox33), UannulerAjoutButton);
  gtk_widget_set_size_request (UannulerAjoutButton, 219, 58);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (UannulerAjoutButton), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox7), label20, FALSE, FALSE, 0);

  eventbox34 = gtk_event_box_new ();
  gtk_widget_show (eventbox34);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox34, 592, 752);
  gtk_widget_set_size_request (eventbox34, 219, 58);

  UajoutButton = gtk_button_new ();
  gtk_widget_show (UajoutButton);
  gtk_container_add (GTK_CONTAINER (eventbox34), UajoutButton);
  gtk_widget_set_size_request (UajoutButton, 219, 58);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (UajoutButton), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox8), label21, FALSE, FALSE, 0);

  eventbox35 = gtk_event_box_new ();
  gtk_widget_show (eventbox35);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox35, 568, 24);
  gtk_widget_set_size_request (eventbox35, 336, 208);

  image21 = create_pixmap (Uajoute, "image-removebg-preview.png");
  gtk_widget_show (image21);
  gtk_container_add (GTK_CONTAINER (eventbox35), image21);
  gtk_widget_set_size_request (image21, 336, 208);

  image22 = create_pixmap (Uajoute, "Screenshot_2023-10-30_123530-removebg.png");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed2), image22, 0, 0);
  gtk_widget_set_size_request (image22, 976, 968);

  g_signal_connect ((gpointer) UgenreHommeAjout, "toggled",
                    G_CALLBACK (on_UgenreHommeAjout_toggled),
                    NULL);
  g_signal_connect ((gpointer) UgenreFemmeAjout, "toggled",
                    G_CALLBACK (on_UgenreFemmeAjout_toggled),
                    NULL);
  g_signal_connect ((gpointer) UafficherMdpAjout, "toggled",
                    G_CALLBACK (on_UafficherMdpAjout_toggled),
                    NULL);
  g_signal_connect ((gpointer) UannulerAjoutButton, "clicked",
                    G_CALLBACK (on_UannulerAjoutButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) UajoutButton, "clicked",
                    G_CALLBACK (on_UajoutButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Uajoute, Uajoute, "Uajoute");
  GLADE_HOOKUP_OBJECT (Uajoute, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Uajoute, UcinEntryAjout, "UcinEntryAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, UnomEntryAjout, "UnomEntryAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, UjjSpinAjout, "UjjSpinAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, UmmSpinAjout, "UmmSpinAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, UyySpinAjout, "UyySpinAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, UprenomEntryAjout, "UprenomEntryAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, UnumEntryAjout, "UnumEntryAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, UloginEntryAjout, "UloginEntryAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, UmdpEntryAjout, "UmdpEntryAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox13, "eventbox13");
  GLADE_HOOKUP_OBJECT (Uajoute, label19, "label19");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox14, "eventbox14");
  GLADE_HOOKUP_OBJECT (Uajoute, label9, "label9");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox15, "eventbox15");
  GLADE_HOOKUP_OBJECT (Uajoute, label8, "label8");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox16, "eventbox16");
  GLADE_HOOKUP_OBJECT (Uajoute, label36, "label36");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox17, "eventbox17");
  GLADE_HOOKUP_OBJECT (Uajoute, label14, "label14");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox18, "eventbox18");
  GLADE_HOOKUP_OBJECT (Uajoute, label11, "label11");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox19, "eventbox19");
  GLADE_HOOKUP_OBJECT (Uajoute, label12, "label12");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox20, "eventbox20");
  GLADE_HOOKUP_OBJECT (Uajoute, label13, "label13");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox21, "eventbox21");
  GLADE_HOOKUP_OBJECT (Uajoute, label15, "label15");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox22, "eventbox22");
  GLADE_HOOKUP_OBJECT (Uajoute, UgenreHommeAjout, "UgenreHommeAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox23, "eventbox23");
  GLADE_HOOKUP_OBJECT (Uajoute, UgenreFemmeAjout, "UgenreFemmeAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox24, "eventbox24");
  GLADE_HOOKUP_OBJECT (Uajoute, label16, "label16");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox25, "eventbox25");
  GLADE_HOOKUP_OBJECT (Uajoute, UregionComboAjout, "UregionComboAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox26, "eventbox26");
  GLADE_HOOKUP_OBJECT (Uajoute, label17, "label17");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (Uajoute, label18, "label18");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox28, "eventbox28");
  GLADE_HOOKUP_OBJECT (Uajoute, UroleComboAjout, "UroleComboAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox29, "eventbox29");
  GLADE_HOOKUP_OBJECT (Uajoute, label37, "label37");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox30, "eventbox30");
  GLADE_HOOKUP_OBJECT (Uajoute, label38, "label38");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox31, "eventbox31");
  GLADE_HOOKUP_OBJECT (Uajoute, UafficherMdpAjout, "UafficherMdpAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox32, "eventbox32");
  GLADE_HOOKUP_OBJECT (Uajoute, UcontroleSaisiAjout, "UcontroleSaisiAjout");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox33, "eventbox33");
  GLADE_HOOKUP_OBJECT (Uajoute, UannulerAjoutButton, "UannulerAjoutButton");
  GLADE_HOOKUP_OBJECT (Uajoute, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Uajoute, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Uajoute, image8, "image8");
  GLADE_HOOKUP_OBJECT (Uajoute, label20, "label20");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox34, "eventbox34");
  GLADE_HOOKUP_OBJECT (Uajoute, UajoutButton, "UajoutButton");
  GLADE_HOOKUP_OBJECT (Uajoute, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Uajoute, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Uajoute, image9, "image9");
  GLADE_HOOKUP_OBJECT (Uajoute, label21, "label21");
  GLADE_HOOKUP_OBJECT (Uajoute, eventbox35, "eventbox35");
  GLADE_HOOKUP_OBJECT (Uajoute, image21, "image21");
  GLADE_HOOKUP_OBJECT (Uajoute, image22, "image22");

  return Uajoute;
}

GtkWidget*
create_Usupprime (void)
{
  GtkWidget *Usupprime;
  GtkWidget *fixed3;
  GtkWidget *UidEntrySupprimer;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *UcontroleSaisiSupprimer;
  GtkWidget *UsupprimerButton;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image10;
  GtkWidget *label25;
  GtkWidget *UannulerSupprimerButton;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label26;

  Usupprime = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Usupprime, 479, 283);
  gtk_window_set_title (GTK_WINDOW (Usupprime), _("Supprimer un utilisateur"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Usupprime), fixed3);

  UidEntrySupprimer = gtk_entry_new ();
  gtk_widget_show (UidEntrySupprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), UidEntrySupprimer, 168, 104);
  gtk_widget_set_size_request (UidEntrySupprimer, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UidEntrySupprimer), 8226);

  label23 = gtk_label_new (_("CIN"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 88, 112);
  gtk_widget_set_size_request (label23, 49, 17);

  label24 = gtk_label_new (_("Supprimer un utilisateur"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 160, 48);
  gtk_widget_set_size_request (label24, 179, 17);

  UcontroleSaisiSupprimer = gtk_label_new ("");
  gtk_widget_show (UcontroleSaisiSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), UcontroleSaisiSupprimer, 112, 160);
  gtk_widget_set_size_request (UcontroleSaisiSupprimer, 300, 23);

  UsupprimerButton = gtk_button_new ();
  gtk_widget_show (UsupprimerButton);
  gtk_fixed_put (GTK_FIXED (fixed3), UsupprimerButton, 264, 208);
  gtk_widget_set_size_request (UsupprimerButton, 150, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (UsupprimerButton), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image10 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox9), image10, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox9), label25, FALSE, FALSE, 0);

  UannulerSupprimerButton = gtk_button_new ();
  gtk_widget_show (UannulerSupprimerButton);
  gtk_fixed_put (GTK_FIXED (fixed3), UannulerSupprimerButton, 104, 208);
  gtk_widget_set_size_request (UannulerSupprimerButton, 150, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (UannulerSupprimerButton), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox10), label26, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) UsupprimerButton, "clicked",
                    G_CALLBACK (on_UsupprimerButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) UannulerSupprimerButton, "clicked",
                    G_CALLBACK (on_UannulerSupprimerButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Usupprime, Usupprime, "Usupprime");
  GLADE_HOOKUP_OBJECT (Usupprime, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Usupprime, UidEntrySupprimer, "UidEntrySupprimer");
  GLADE_HOOKUP_OBJECT (Usupprime, label23, "label23");
  GLADE_HOOKUP_OBJECT (Usupprime, label24, "label24");
  GLADE_HOOKUP_OBJECT (Usupprime, UcontroleSaisiSupprimer, "UcontroleSaisiSupprimer");
  GLADE_HOOKUP_OBJECT (Usupprime, UsupprimerButton, "UsupprimerButton");
  GLADE_HOOKUP_OBJECT (Usupprime, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Usupprime, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Usupprime, image10, "image10");
  GLADE_HOOKUP_OBJECT (Usupprime, label25, "label25");
  GLADE_HOOKUP_OBJECT (Usupprime, UannulerSupprimerButton, "UannulerSupprimerButton");
  GLADE_HOOKUP_OBJECT (Usupprime, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Usupprime, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Usupprime, image11, "image11");
  GLADE_HOOKUP_OBJECT (Usupprime, label26, "label26");

  return Usupprime;
}

GtkWidget*
create_Ustatistique (void)
{
  GtkWidget *Ustatistique;
  GtkWidget *fixed4;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label33;
  GtkWidget *UpourcentageHommeLabelStatistique;
  GtkWidget *UpourcentageFemmeLabelStatistique;
  GtkWidget *FDstatistiqueButton;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image13;
  GtkWidget *label34;
  GtkWidget *UannulerStatistiqueButton;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label35;

  Ustatistique = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Ustatistique, 406, 308);
  gtk_window_set_title (GTK_WINDOW (Ustatistique), _("La Statistique"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Ustatistique), fixed4);

  label29 = gtk_label_new (_("Pourcentage Homme :"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 16, 88);
  gtk_widget_set_size_request (label29, 184, 17);

  label30 = gtk_label_new (_("Poucentage Femme :"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 16, 136);
  gtk_widget_set_size_request (label30, 178, 17);

  label33 = gtk_label_new (_("La Statistique"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 160, 40);
  gtk_widget_set_size_request (label33, 106, 17);

  UpourcentageHommeLabelStatistique = gtk_label_new ("");
  gtk_widget_show (UpourcentageHommeLabelStatistique);
  gtk_fixed_put (GTK_FIXED (fixed4), UpourcentageHommeLabelStatistique, 208, 88);
  gtk_widget_set_size_request (UpourcentageHommeLabelStatistique, 49, 17);

  UpourcentageFemmeLabelStatistique = gtk_label_new ("");
  gtk_widget_show (UpourcentageFemmeLabelStatistique);
  gtk_fixed_put (GTK_FIXED (fixed4), UpourcentageFemmeLabelStatistique, 208, 136);
  gtk_widget_set_size_request (UpourcentageFemmeLabelStatistique, 49, 17);

  FDstatistiqueButton = gtk_button_new ();
  gtk_widget_show (FDstatistiqueButton);
  gtk_fixed_put (GTK_FIXED (fixed4), FDstatistiqueButton, 216, 224);
  gtk_widget_set_size_request (FDstatistiqueButton, 157, 39);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (FDstatistiqueButton), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image13 = gtk_image_new_from_stock ("gtk-select-color", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox12), image13, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Afficher Pour"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox12), label34, FALSE, FALSE, 0);

  UannulerStatistiqueButton = gtk_button_new ();
  gtk_widget_show (UannulerStatistiqueButton);
  gtk_fixed_put (GTK_FIXED (fixed4), UannulerStatistiqueButton, 56, 224);
  gtk_widget_set_size_request (UannulerStatistiqueButton, 122, 39);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (UannulerStatistiqueButton), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox13), label35, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) FDstatistiqueButton, "clicked",
                    G_CALLBACK (on_FDstatistiqueButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) UannulerStatistiqueButton, "clicked",
                    G_CALLBACK (on_UannulerStatistiqueButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ustatistique, Ustatistique, "Ustatistique");
  GLADE_HOOKUP_OBJECT (Ustatistique, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Ustatistique, label29, "label29");
  GLADE_HOOKUP_OBJECT (Ustatistique, label30, "label30");
  GLADE_HOOKUP_OBJECT (Ustatistique, label33, "label33");
  GLADE_HOOKUP_OBJECT (Ustatistique, UpourcentageHommeLabelStatistique, "UpourcentageHommeLabelStatistique");
  GLADE_HOOKUP_OBJECT (Ustatistique, UpourcentageFemmeLabelStatistique, "UpourcentageFemmeLabelStatistique");
  GLADE_HOOKUP_OBJECT (Ustatistique, FDstatistiqueButton, "FDstatistiqueButton");
  GLADE_HOOKUP_OBJECT (Ustatistique, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Ustatistique, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Ustatistique, image13, "image13");
  GLADE_HOOKUP_OBJECT (Ustatistique, label34, "label34");
  GLADE_HOOKUP_OBJECT (Ustatistique, UannulerStatistiqueButton, "UannulerStatistiqueButton");
  GLADE_HOOKUP_OBJECT (Ustatistique, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Ustatistique, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Ustatistique, image14, "image14");
  GLADE_HOOKUP_OBJECT (Ustatistique, label35, "label35");

  return Ustatistique;
}

GtkWidget*
create_Umodife (void)
{
  GtkWidget *Umodife;
  GtkWidget *fixed5;
  GtkWidget *UcinEntryModifier;
  GtkWidget *UnomEntryModifier;
  GtkObject *UjjSpinModifier_adj;
  GtkWidget *UjjSpinModifier;
  GtkObject *UmmSpinModifier_adj;
  GtkWidget *UmmSpinModifier;
  GtkObject *UyySpinModifier_adj;
  GtkWidget *UyySpinModifier;
  GtkWidget *UprenomEntryModifier;
  GtkWidget *UnumEntryModifier;
  GtkWidget *UloginEntryModifier;
  GtkWidget *UmdpEntryModifier;
  GtkWidget *eventbox36;
  GtkWidget *label45;
  GtkWidget *eventbox37;
  GtkWidget *label46;
  GtkWidget *eventbox38;
  GtkWidget *UbuttonRechercherIDModifier;
  GtkWidget *image17;
  GtkWidget *eventbox39;
  GtkWidget *label47;
  GtkWidget *eventbox40;
  GtkWidget *label48;
  GtkWidget *eventbox41;
  GtkWidget *label42;
  GtkWidget *eventbox42;
  GtkWidget *label39;
  GtkWidget *eventbox43;
  GtkWidget *label40;
  GtkWidget *eventbox44;
  GtkWidget *label41;
  GtkWidget *eventbox45;
  GtkWidget *label49;
  GtkWidget *eventbox46;
  GtkWidget *UgenreHommeModifier;
  GSList *UgenreHommeModifier_group = NULL;
  GtkWidget *eventbox47;
  GtkWidget *UgenreFemmeModifier;
  GtkWidget *eventbox48;
  GtkWidget *label50;
  GtkWidget *eventbox49;
  GtkWidget *UregionComboModifier;
  GtkWidget *eventbox50;
  GtkWidget *label51;
  GtkWidget *eventbox51;
  GtkWidget *label52;
  GtkWidget *eventbox52;
  GtkWidget *UroleComboModifier;
  GtkWidget *eventbox53;
  GtkWidget *label53;
  GtkWidget *eventbox54;
  GtkWidget *label54;
  GtkWidget *eventbox55;
  GtkWidget *UafficherMdpModifier;
  GtkWidget *eventbox56;
  GtkWidget *UcontroleSaisiModifier;
  GtkWidget *eventbox57;
  GtkWidget *UannulerModifierButton;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label43;
  GtkWidget *eventbox58;
  GtkWidget *UModifierButton;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image18;
  GtkWidget *label56;
  GtkWidget *eventbox59;
  GtkWidget *image23;
  GtkWidget *image24;

  Umodife = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Umodife, 921, 897);
  gtk_window_set_title (GTK_WINDOW (Umodife), _("Modifier d'un utilisateur"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Umodife), fixed5);

  UcinEntryModifier = gtk_entry_new ();
  gtk_widget_show (UcinEntryModifier);
  gtk_fixed_put (GTK_FIXED (fixed5), UcinEntryModifier, 344, 144);
  gtk_widget_set_size_request (UcinEntryModifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UcinEntryModifier), 8226);

  UnomEntryModifier = gtk_entry_new ();
  gtk_widget_show (UnomEntryModifier);
  gtk_fixed_put (GTK_FIXED (fixed5), UnomEntryModifier, 344, 192);
  gtk_widget_set_size_request (UnomEntryModifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UnomEntryModifier), 8226);

  UjjSpinModifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  UjjSpinModifier = gtk_spin_button_new (GTK_ADJUSTMENT (UjjSpinModifier_adj), 1, 0);
  gtk_widget_show (UjjSpinModifier);
  gtk_fixed_put (GTK_FIXED (fixed5), UjjSpinModifier, 368, 344);
  gtk_widget_set_size_request (UjjSpinModifier, 60, 27);

  UmmSpinModifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  UmmSpinModifier = gtk_spin_button_new (GTK_ADJUSTMENT (UmmSpinModifier_adj), 1, 0);
  gtk_widget_show (UmmSpinModifier);
  gtk_fixed_put (GTK_FIXED (fixed5), UmmSpinModifier, 536, 344);
  gtk_widget_set_size_request (UmmSpinModifier, 60, 27);

  UyySpinModifier_adj = gtk_adjustment_new (2023, 1950, 2024, 1, 10, 10);
  UyySpinModifier = gtk_spin_button_new (GTK_ADJUSTMENT (UyySpinModifier_adj), 1, 0);
  gtk_widget_show (UyySpinModifier);
  gtk_fixed_put (GTK_FIXED (fixed5), UyySpinModifier, 720, 344);
  gtk_widget_set_size_request (UyySpinModifier, 60, 27);

  UprenomEntryModifier = gtk_entry_new ();
  gtk_widget_show (UprenomEntryModifier);
  gtk_fixed_put (GTK_FIXED (fixed5), UprenomEntryModifier, 344, 248);
  gtk_widget_set_size_request (UprenomEntryModifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UprenomEntryModifier), 8226);

  UnumEntryModifier = gtk_entry_new ();
  gtk_widget_show (UnumEntryModifier);
  gtk_fixed_put (GTK_FIXED (fixed5), UnumEntryModifier, 312, 520);
  gtk_widget_set_size_request (UnumEntryModifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UnumEntryModifier), 8226);

  UloginEntryModifier = gtk_entry_new ();
  gtk_widget_show (UloginEntryModifier);
  gtk_fixed_put (GTK_FIXED (fixed5), UloginEntryModifier, 328, 624);
  gtk_widget_set_size_request (UloginEntryModifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (UloginEntryModifier), 8226);

  UmdpEntryModifier = gtk_entry_new ();
  gtk_widget_show (UmdpEntryModifier);
  gtk_fixed_put (GTK_FIXED (fixed5), UmdpEntryModifier, 328, 680);
  gtk_widget_set_size_request (UmdpEntryModifier, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (UmdpEntryModifier), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (UmdpEntryModifier), 8226);

  eventbox36 = gtk_event_box_new ();
  gtk_widget_show (eventbox36);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox36, 304, 56);
  gtk_widget_set_size_request (eventbox36, 300, 17);

  label45 = gtk_label_new (_("Modifier un utilisateur"));
  gtk_widget_show (label45);
  gtk_container_add (GTK_CONTAINER (eventbox36), label45);
  gtk_widget_set_size_request (label45, 300, 17);

  eventbox37 = gtk_event_box_new ();
  gtk_widget_show (eventbox37);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox37, 280, 152);
  gtk_widget_set_size_request (eventbox37, 49, 17);

  label46 = gtk_label_new (_("Cin"));
  gtk_widget_show (label46);
  gtk_container_add (GTK_CONTAINER (eventbox37), label46);
  gtk_widget_set_size_request (label46, 49, 17);

  eventbox38 = gtk_event_box_new ();
  gtk_widget_show (eventbox38);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox38, 512, 144);
  gtk_widget_set_size_request (eventbox38, 40, 29);

  UbuttonRechercherIDModifier = gtk_button_new ();
  gtk_widget_show (UbuttonRechercherIDModifier);
  gtk_container_add (GTK_CONTAINER (eventbox38), UbuttonRechercherIDModifier);
  gtk_widget_set_size_request (UbuttonRechercherIDModifier, 40, 29);

  image17 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (UbuttonRechercherIDModifier), image17);

  eventbox39 = gtk_event_box_new ();
  gtk_widget_show (eventbox39);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox39, 272, 200);
  gtk_widget_set_size_request (eventbox39, 49, 17);

  label47 = gtk_label_new (_("Nom"));
  gtk_widget_show (label47);
  gtk_container_add (GTK_CONTAINER (eventbox39), label47);
  gtk_widget_set_size_request (label47, 49, 17);

  eventbox40 = gtk_event_box_new ();
  gtk_widget_show (eventbox40);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox40, 256, 256);
  gtk_widget_set_size_request (eventbox40, 54, 17);

  label48 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label48);
  gtk_container_add (GTK_CONTAINER (eventbox40), label48);
  gtk_widget_set_size_request (label48, 54, 17);

  eventbox41 = gtk_event_box_new ();
  gtk_widget_show (eventbox41);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox41, 208, 352);
  gtk_widget_set_size_request (eventbox41, 49, 17);

  label42 = gtk_label_new (_("Date"));
  gtk_widget_show (label42);
  gtk_container_add (GTK_CONTAINER (eventbox41), label42);
  gtk_widget_set_size_request (label42, 49, 17);

  eventbox42 = gtk_event_box_new ();
  gtk_widget_show (eventbox42);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox42, 296, 352);
  gtk_widget_set_size_request (eventbox42, 49, 17);

  label39 = gtk_label_new (_("Jour"));
  gtk_widget_show (label39);
  gtk_container_add (GTK_CONTAINER (eventbox42), label39);
  gtk_widget_set_size_request (label39, 49, 17);

  eventbox43 = gtk_event_box_new ();
  gtk_widget_show (eventbox43);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox43, 480, 352);
  gtk_widget_set_size_request (eventbox43, 49, 17);

  label40 = gtk_label_new (_("Mois"));
  gtk_widget_show (label40);
  gtk_container_add (GTK_CONTAINER (eventbox43), label40);
  gtk_widget_set_size_request (label40, 49, 17);

  eventbox44 = gtk_event_box_new ();
  gtk_widget_show (eventbox44);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox44, 656, 352);
  gtk_widget_set_size_request (eventbox44, 49, 17);

  label41 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label41);
  gtk_container_add (GTK_CONTAINER (eventbox44), label41);
  gtk_widget_set_size_request (label41, 49, 17);

  eventbox45 = gtk_event_box_new ();
  gtk_widget_show (eventbox45);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox45, 208, 408);
  gtk_widget_set_size_request (eventbox45, 49, 17);

  label49 = gtk_label_new (_("Genre"));
  gtk_widget_show (label49);
  gtk_container_add (GTK_CONTAINER (eventbox45), label49);
  gtk_widget_set_size_request (label49, 49, 17);

  eventbox46 = gtk_event_box_new ();
  gtk_widget_show (eventbox46);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox46, 304, 408);
  gtk_widget_set_size_request (eventbox46, 116, 24);

  UgenreHommeModifier = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (UgenreHommeModifier);
  gtk_container_add (GTK_CONTAINER (eventbox46), UgenreHommeModifier);
  gtk_widget_set_size_request (UgenreHommeModifier, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (UgenreHommeModifier), UgenreHommeModifier_group);
  UgenreHommeModifier_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (UgenreHommeModifier));

  eventbox47 = gtk_event_box_new ();
  gtk_widget_show (eventbox47);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox47, 424, 408);
  gtk_widget_set_size_request (eventbox47, 116, 24);

  UgenreFemmeModifier = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (UgenreFemmeModifier);
  gtk_container_add (GTK_CONTAINER (eventbox47), UgenreFemmeModifier);
  gtk_widget_set_size_request (UgenreFemmeModifier, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (UgenreFemmeModifier), UgenreHommeModifier_group);
  UgenreHommeModifier_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (UgenreFemmeModifier));

  eventbox48 = gtk_event_box_new ();
  gtk_widget_show (eventbox48);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox48, 208, 464);
  gtk_widget_set_size_request (eventbox48, 73, 17);

  label50 = gtk_label_new (_("Region"));
  gtk_widget_show (label50);
  gtk_container_add (GTK_CONTAINER (eventbox48), label50);
  gtk_widget_set_size_request (label50, 73, 17);

  eventbox49 = gtk_event_box_new ();
  gtk_widget_show (eventbox49);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox49, 304, 456);
  gtk_widget_set_size_request (eventbox49, 189, 29);

  UregionComboModifier = gtk_combo_box_entry_new_text ();
  gtk_widget_show (UregionComboModifier);
  gtk_container_add (GTK_CONTAINER (eventbox49), UregionComboModifier);
  gtk_widget_set_size_request (UregionComboModifier, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Beja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Ben arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Tataouine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Touzeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Jandouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Zaghouane"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Seliana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Sidi bouzid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Gabes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Gebelli"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("kasserine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Gafsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("kairaouane"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Mednine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Mannouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UregionComboModifier), _("Nabeul"));

  eventbox50 = gtk_event_box_new ();
  gtk_widget_show (eventbox50);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox50, 208, 528);
  gtk_widget_set_size_request (eventbox50, 88, 17);

  label51 = gtk_label_new (_("Telephone"));
  gtk_widget_show (label51);
  gtk_container_add (GTK_CONTAINER (eventbox50), label51);
  gtk_widget_set_size_request (label51, 88, 17);

  eventbox51 = gtk_event_box_new ();
  gtk_widget_show (eventbox51);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox51, 216, 584);
  gtk_widget_set_size_request (eventbox51, 72, 17);

  label52 = gtk_label_new (_("Role"));
  gtk_widget_show (label52);
  gtk_container_add (GTK_CONTAINER (eventbox51), label52);
  gtk_widget_set_size_request (label52, 72, 17);

  eventbox52 = gtk_event_box_new ();
  gtk_widget_show (eventbox52);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox52, 312, 576);
  gtk_widget_set_size_request (eventbox52, 189, 29);

  UroleComboModifier = gtk_combo_box_entry_new_text ();
  gtk_widget_show (UroleComboModifier);
  gtk_container_add (GTK_CONTAINER (eventbox52), UroleComboModifier);
  gtk_widget_set_size_request (UroleComboModifier, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (UroleComboModifier), _("medecin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UroleComboModifier), _("infemier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (UroleComboModifier), _("ets"));

  eventbox53 = gtk_event_box_new ();
  gtk_widget_show (eventbox53);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox53, 240, 632);
  gtk_widget_set_size_request (eventbox53, 49, 17);

  label53 = gtk_label_new (_("Login"));
  gtk_widget_show (label53);
  gtk_container_add (GTK_CONTAINER (eventbox53), label53);
  gtk_widget_set_size_request (label53, 49, 17);

  eventbox54 = gtk_event_box_new ();
  gtk_widget_show (eventbox54);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox54, 208, 680);
  gtk_widget_set_size_request (eventbox54, 113, 17);

  label54 = gtk_label_new (_("Mot de passe "));
  gtk_widget_show (label54);
  gtk_container_add (GTK_CONTAINER (eventbox54), label54);
  gtk_widget_set_size_request (label54, 113, 17);

  eventbox55 = gtk_event_box_new ();
  gtk_widget_show (eventbox55);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox55, 520, 680);
  gtk_widget_set_size_request (eventbox55, 181, 24);

  UafficherMdpModifier = gtk_check_button_new_with_mnemonic (_("Afficher le mot de passe"));
  gtk_widget_show (UafficherMdpModifier);
  gtk_container_add (GTK_CONTAINER (eventbox55), UafficherMdpModifier);
  gtk_widget_set_size_request (UafficherMdpModifier, 181, 24);

  eventbox56 = gtk_event_box_new ();
  gtk_widget_show (eventbox56);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox56, 312, 720);
  gtk_widget_set_size_request (eventbox56, 300, 30);

  UcontroleSaisiModifier = gtk_label_new ("");
  gtk_widget_show (UcontroleSaisiModifier);
  gtk_container_add (GTK_CONTAINER (eventbox56), UcontroleSaisiModifier);
  gtk_widget_set_size_request (UcontroleSaisiModifier, 300, 30);

  eventbox57 = gtk_event_box_new ();
  gtk_widget_show (eventbox57);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox57, 224, 752);
  gtk_widget_set_size_request (eventbox57, 219, 58);

  UannulerModifierButton = gtk_button_new ();
  gtk_widget_show (UannulerModifierButton);
  gtk_container_add (GTK_CONTAINER (eventbox57), UannulerModifierButton);
  gtk_widget_set_size_request (UannulerModifierButton, 219, 58);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (UannulerModifierButton), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox14), label43, FALSE, FALSE, 0);

  eventbox58 = gtk_event_box_new ();
  gtk_widget_show (eventbox58);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox58, 592, 752);
  gtk_widget_set_size_request (eventbox58, 219, 58);

  UModifierButton = gtk_button_new ();
  gtk_widget_show (UModifierButton);
  gtk_container_add (GTK_CONTAINER (eventbox58), UModifierButton);
  gtk_widget_set_size_request (UModifierButton, 219, 58);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (UModifierButton), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image18 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox15), image18, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox15), label56, FALSE, FALSE, 0);

  eventbox59 = gtk_event_box_new ();
  gtk_widget_show (eventbox59);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox59, 648, 8);
  gtk_widget_set_size_request (eventbox59, 208, 176);

  image23 = create_pixmap (Umodife, "image-removebg-preview.png");
  gtk_widget_show (image23);
  gtk_container_add (GTK_CONTAINER (eventbox59), image23);
  gtk_widget_set_size_request (image23, 208, 176);

  image24 = create_pixmap (Umodife, "Screenshot_2023-10-30_123530-removebg.png");
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed5), image24, 0, 0);
  gtk_widget_set_size_request (image24, 936, 920);

  g_signal_connect ((gpointer) UbuttonRechercherIDModifier, "clicked",
                    G_CALLBACK (on_UbuttonRechercherIDModifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) UgenreHommeModifier, "toggled",
                    G_CALLBACK (on_UgenreHommeModifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) UgenreFemmeModifier, "toggled",
                    G_CALLBACK (on_UgenreFemmeModifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) UafficherMdpModifier, "toggled",
                    G_CALLBACK (on_UafficherMdpModifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) UannulerModifierButton, "clicked",
                    G_CALLBACK (on_UannulerModifierButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) UModifierButton, "clicked",
                    G_CALLBACK (on_UModifierButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Umodife, Umodife, "Umodife");
  GLADE_HOOKUP_OBJECT (Umodife, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Umodife, UcinEntryModifier, "UcinEntryModifier");
  GLADE_HOOKUP_OBJECT (Umodife, UnomEntryModifier, "UnomEntryModifier");
  GLADE_HOOKUP_OBJECT (Umodife, UjjSpinModifier, "UjjSpinModifier");
  GLADE_HOOKUP_OBJECT (Umodife, UmmSpinModifier, "UmmSpinModifier");
  GLADE_HOOKUP_OBJECT (Umodife, UyySpinModifier, "UyySpinModifier");
  GLADE_HOOKUP_OBJECT (Umodife, UprenomEntryModifier, "UprenomEntryModifier");
  GLADE_HOOKUP_OBJECT (Umodife, UnumEntryModifier, "UnumEntryModifier");
  GLADE_HOOKUP_OBJECT (Umodife, UloginEntryModifier, "UloginEntryModifier");
  GLADE_HOOKUP_OBJECT (Umodife, UmdpEntryModifier, "UmdpEntryModifier");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox36, "eventbox36");
  GLADE_HOOKUP_OBJECT (Umodife, label45, "label45");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox37, "eventbox37");
  GLADE_HOOKUP_OBJECT (Umodife, label46, "label46");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox38, "eventbox38");
  GLADE_HOOKUP_OBJECT (Umodife, UbuttonRechercherIDModifier, "UbuttonRechercherIDModifier");
  GLADE_HOOKUP_OBJECT (Umodife, image17, "image17");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox39, "eventbox39");
  GLADE_HOOKUP_OBJECT (Umodife, label47, "label47");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox40, "eventbox40");
  GLADE_HOOKUP_OBJECT (Umodife, label48, "label48");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox41, "eventbox41");
  GLADE_HOOKUP_OBJECT (Umodife, label42, "label42");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox42, "eventbox42");
  GLADE_HOOKUP_OBJECT (Umodife, label39, "label39");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox43, "eventbox43");
  GLADE_HOOKUP_OBJECT (Umodife, label40, "label40");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox44, "eventbox44");
  GLADE_HOOKUP_OBJECT (Umodife, label41, "label41");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox45, "eventbox45");
  GLADE_HOOKUP_OBJECT (Umodife, label49, "label49");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox46, "eventbox46");
  GLADE_HOOKUP_OBJECT (Umodife, UgenreHommeModifier, "UgenreHommeModifier");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox47, "eventbox47");
  GLADE_HOOKUP_OBJECT (Umodife, UgenreFemmeModifier, "UgenreFemmeModifier");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox48, "eventbox48");
  GLADE_HOOKUP_OBJECT (Umodife, label50, "label50");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox49, "eventbox49");
  GLADE_HOOKUP_OBJECT (Umodife, UregionComboModifier, "UregionComboModifier");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox50, "eventbox50");
  GLADE_HOOKUP_OBJECT (Umodife, label51, "label51");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox51, "eventbox51");
  GLADE_HOOKUP_OBJECT (Umodife, label52, "label52");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox52, "eventbox52");
  GLADE_HOOKUP_OBJECT (Umodife, UroleComboModifier, "UroleComboModifier");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox53, "eventbox53");
  GLADE_HOOKUP_OBJECT (Umodife, label53, "label53");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox54, "eventbox54");
  GLADE_HOOKUP_OBJECT (Umodife, label54, "label54");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox55, "eventbox55");
  GLADE_HOOKUP_OBJECT (Umodife, UafficherMdpModifier, "UafficherMdpModifier");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox56, "eventbox56");
  GLADE_HOOKUP_OBJECT (Umodife, UcontroleSaisiModifier, "UcontroleSaisiModifier");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox57, "eventbox57");
  GLADE_HOOKUP_OBJECT (Umodife, UannulerModifierButton, "UannulerModifierButton");
  GLADE_HOOKUP_OBJECT (Umodife, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Umodife, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Umodife, image15, "image15");
  GLADE_HOOKUP_OBJECT (Umodife, label43, "label43");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox58, "eventbox58");
  GLADE_HOOKUP_OBJECT (Umodife, UModifierButton, "UModifierButton");
  GLADE_HOOKUP_OBJECT (Umodife, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Umodife, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Umodife, image18, "image18");
  GLADE_HOOKUP_OBJECT (Umodife, label56, "label56");
  GLADE_HOOKUP_OBJECT (Umodife, eventbox59, "eventbox59");
  GLADE_HOOKUP_OBJECT (Umodife, image23, "image23");
  GLADE_HOOKUP_OBJECT (Umodife, image24, "image24");

  return Umodife;
}

