/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Uaffiche (void);
GtkWidget* create_Uajoute (void);
GtkWidget* create_Usupprime (void);
GtkWidget* create_Ustatistique (void);
GtkWidget* create_Umodife (void);
